url: https://marijnkoolen.github.io/dir2017
baseurl: /dir2017
# Site settings
title: "DIR2017"
email: marijn.koolen@gmail.com
description: "Dutch-Belgian Information Retrieval Workshop 2017."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/_DIR2017

# Build settings
markdown: kramdown
permalink: pretty
